# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - sssrrreeee

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://springgtraillls.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_dd02f6e370264c0f8ca1cbc72dba2489 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9067699f37c0418c9186360fda723318 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: springgtraillls.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dd02f6e370264c0f8ca1cbc72dba2489 }}/sppprrrr:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sssrrreeee'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b37b12180df54f68b52df355ce413246 }}
        images: 'springgtraillls.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dd02f6e370264c0f8ca1cbc72dba2489 }}/sppprrrr:${{ github.sha }}'