# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - nikiaryall

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://nikiarya.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e583162768274993b19f601e1cf8636e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_36472efb653040e2b2e729c940b3812e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: nikiarya.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e583162768274993b19f601e1cf8636e }}/nikiaryya:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'nikiaryall'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_beb4ac2ba4df47d0bca297d6083a5f29 }}
        images: 'nikiarya.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e583162768274993b19f601e1cf8636e }}/nikiaryya:${{ github.sha }}'